[build-system]
requires = ["setuptools==76.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cognichem-client"
version = "0.1.1"
description = "Python client for the CogniChem API"
authors = [
    { name = "Travis Kessler", email = "travis@cognichem.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests",
]

[project.urls]
Homepage = "https://github.com/Cognitive-Chemistry-Labs/cognichem-client-python"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["cognichem_client.egg-info"]

[tool.setuptools]
include-package-data = true